/**
 * @author @l.piciollo
 * @email lucapiciolo@gmail.com
 * @create date 2019-12-22 18:15:21
 * @modify date 2019-12-22 18:15:21
 * @desc [eventi esportati per la parte core applicativa]
 */
export  enum CORE_TYPE_EVENT {
    CORE_HTTP_AJAX_ERROR = "CORE:HTTP-AJAX-ERROR",
    CORE_HTTP_AJAX_CACHE="CORE:HTTP_AJAX_CACHE",
    CORE_HTTP_AJAX_AUTENTICATE_KO = "CORE:HTTP-AJAX-AUTENTICATE-KO",
    CORE_ERROR_SERVICE_REDIRECT = "CORE:ERROR_SERVICE_REDIRECT",
    CORE_ERROR_SERVICE_DIALOG = "CORE:ERROR_SERVICE_DIALOG",
    CORE_ACQUIRE_TOKEN_SUCCESS = "CORE:ACQUIRE_TOKEN_SUCCESS",
    CORE_LOGIN_SUCCESS= "CORE:LOGIN_SUCCESS",
    CORE_ERROR_SERVICE="CORE:ERROR_SERVICE"
}